# Generated by Django 5.2.11 on 2026-03-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('interviewed_by', models.IntegerField(max_length=100)),
                ('esi_check_by', models.IntegerField(max_length=100)),
                ('onboarded_by', models.IntegerField(max_length=100)),
                ('corporation', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('notes', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member_state', models.CharField(max_length=100)),
                ('num_of_characters', models.IntegerField()),
                ('registry_number', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graduation_date', models.DateField()),
                ('attrition_headcount', models.IntegerField()),
            ],
        ),
    ]
