# Generated by Django 5.2.11 on 2026-03-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='esi_check_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='interviewed_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='onboarded_by',
            field=models.IntegerField(),
        ),
    ]
