# Generated by Django 5.2.11 on 2026-03-09 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_comments_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='esi_check_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='ESI checked by'),
        ),
        migrations.AlterField(
            model_name='member',
            name='num_of_characters',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of characters'),
        ),
    ]
