# Generated by Django 5.2.11 on 2026-03-09 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_comment_user_alter_member_esi_check_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='esi_check_by',
        ),
        migrations.AddField(
            model_name='member',
            name='esi_checked_by',
            field=models.ForeignKey(blank=True, choices=[('test', 2), ('fates', 1)], null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esi_checked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='corporation',
            field=models.CharField(blank=True, choices=[('TL', 'Tidal Lock'), ('VL', 'Vapor Lock.')], default='TL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Recruit', 'Recruit'), ('Member', 'Member'), ('Purged', 'Purged'), ('Rejected', 'Rejected'), ('Declined', 'Declined'), ('Left', 'Left'), ('Kicked', 'Kicked')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='interviewed_by',
            field=models.ForeignKey(blank=True, choices=[('test', 2), ('fates', 1)], null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_state',
            field=models.CharField(blank=True, choices=[('Recruit', 'Recruit'), ('Member', 'Member')], default='Recruit', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='num_of_characters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='onboarded_by',
            field=models.ForeignKey(blank=True, choices=[('test', 2), ('fates', 1)], null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='timezone',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('EU', 'EU'), ('AU', 'AU')], default='US', max_length=100, null=True),
        ),
    ]
