# Generated by Django 5.2.11 on 2026-03-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_member_esi_check_by_member_esi_checked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='corporation',
            field=models.CharField(blank=True, choices=[('TL', 'Tidal Lock'), ('VL', 'Vapor Lock.')], default='TL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Recruit', 'Recruit'), ('Member', 'Member'), ('Purged', 'Purged'), ('Rejected', 'Rejected'), ('Declined', 'Declined'), ('Left', 'Left'), ('Kicked', 'Kicked')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_state',
            field=models.CharField(blank=True, choices=[('Recruit', 'Recruit'), ('Member', 'Member')], default='Recruit', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='timezone',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('EU', 'EU'), ('AU', 'AU')], default='US', max_length=100, null=True),
        ),
    ]
