# Generated by Django 5.2.11 on 2026-03-09 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_member_corporation_alter_member_current_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='esi_checked_by',
            field=models.ForeignKey(blank=True, choices=[(2, 'test'), (1, 'fates')], null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esi_checked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='interviewed_by',
            field=models.ForeignKey(blank=True, choices=[(2, 'test'), (1, 'fates')], null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='onboarded_by',
            field=models.ForeignKey(blank=True, choices=[(2, 'test'), (1, 'fates')], null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
