# Generated by Django 5.2.11 on 2026-03-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_member_esi_checked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='eve_character_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
