# Generated by Django 5.2.11 on 2026-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_member_eve_character_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='attrition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Recruit', 'Recruit'), ('Member', 'Member'), ('Purged', 'Purged'), ('Rejected', 'Rejected'), ('Declined', 'Declined'), ('Voluntary - Other Corporation', 'Voluntary - Other Corporation'), ('Voluntary - Real Life', 'Voluntary - Real Life'), ('Kicked', 'Kicked')], default='Pending', max_length=100, null=True),
        ),
    ]
