# Generated by Django 5.2.11 on 2026-03-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_member_attrition_date_alter_member_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Recruit', 'Recruit'), ('Member', 'Member'), ('Purged', 'Purged'), ('Rejected', 'Rejected'), ('Declined', 'Declined'), ('Voluntary - Other Group', 'Voluntary - Other Group'), ('Voluntary - IRL', 'Voluntary - IRL'), ('Kicked', 'Kicked')], default='Pending', max_length=100, null=True),
        ),
    ]
