# Generated by Django 5.2.11 on 2026-03-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_member_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
